name: basic_ride
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.7.2	

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.4
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  google_maps_flutter: ^2.12.1
  easy_localization: ^3.0.7+1
  flutter_bloc: ^9.1.0
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^3.0.0
  interval_time_picker: ^3.0.3+9
  http: ^1.3.0
  json_annotation: ^4.9.0
  flutter_polyline_points: ^2.1.0
  flutter_dotenv: ^5.2.1
  fluttertoast: ^8.2.12
  geolocator: ^13.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - .env
    - assets/images/